# Generated by Django 4.0.4 on 2022-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driving_licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cepik', models.CharField(max_length=45)),
                ('data_uprawnien', models.CharField(max_length=45)),
                ('id_wojewodztwa', models.IntegerField(default=0)),
                ('wojewodztwo', models.CharField(max_length=45, null=True)),
                ('plec', models.CharField(max_length=12, null=True)),
                ('wiek', models.IntegerField(default=1, null=True)),
                ('ilosc', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cepik', models.IntegerField(default=0)),
                ('marka', models.CharField(max_length=45, null=True)),
                ('model', models.CharField(max_length=45, null=True)),
                ('id_wojewodztwa', models.IntegerField(default=0)),
                ('wojewodztwo', models.CharField(max_length=45, null=True)),
                ('rodzaj_pojazdu', models.CharField(max_length=45, null=True)),
                ('pochodzenie_pojazdu', models.CharField(max_length=45, null=True)),
                ('rok_produkcji', models.CharField(max_length=45, null=True)),
                ('pojemnosc_skokowa', models.DecimalField(decimal_places=1, default=1, max_digits=20, null=True)),
                ('dmc', models.CharField(max_length=45, null=True)),
                ('liczba_miejsc', models.IntegerField(default=1, null=True)),
                ('rodzaj_paliwa', models.CharField(max_length=45, null=True)),
                ('hak', models.BooleanField(default=False)),
                ('kierownica_po_prawej', models.BooleanField(null=True)),
            ],
        ),
    ]
