# Generated by Django 4.0.4 on 2022-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='data_ostatniej_rejestracji_w_kraju',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
