# Generated by Django 4.0.4 on 2022-08-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_vehicle_data_ostatniej_rejestracji_w_kraju'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voivodeship',
            name='id_wojewodztwa',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wojewodztwo_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='viewer.voivodeship'),
        ),
    ]
