# Generated by Django 4.0.4 on 2022-08-10 18:06

from django.db import migrations


def fill_category_fk(apps, schema_editor):
  Vehicle = apps.get_model('viewer', 'Vehicle')
  Voivodeship = apps.get_model('viewer', 'Voivodeship')
  for sample in Vehicle.objects.all():
    sample.wojewodztwo_fk, created = Voivodeship.objects.get_or_create(wojewodztwo=sample.wojewodztwo)
    sample.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_voivodeship_id_wojewodztwa_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_category_fk),
    ]
