# Generated by Django 4.0.4 on 2022-08-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20220810_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='wojewodztwo',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='wojewodztwo_fk',
            new_name='wojewodztwo'),
    ]
